### ISSUE TITLE
Value Error: <my.gvcf.gz> is not a directory.

### ISSUE THREAD

**Issue by CNHAustin** [nch-igm/snvstory#18]
Hello, having an issue where `snvstory` keeps parsing my input gvcf as a directory.

```
directory structure:
dev/
    |
    data/
        |
        resource_dir/
        output/
        NIST8398-20240828.hard-filtered.gvcf.gz
```

command:
```
docker-compose run ancestry --path "data/NIST8398-20240828.hard-filtered.gvcf.gz" --resource "data/resource_dir" --output-dir "/data/NIST_output" --genome-ver 38 --mode WGS`
```

Error:
```
Directory: data/NIST8398-20240828.hard-filtered.gvcf.gz does not appear to be local or an s3 input
Traceback (most recent call last):
  File "/opt/Ancestry/igm_churchill_ancestry/cli.py", line 125, in run_ancestry
    local_vcf_dir = flex_input(args.path, INPUT_DIR, directory=True)
  File "/opt/Ancestry/igm_churchill_ancestry/utilities/flex.py", line 58, in flex_input
    raise ValueError(f"{in_path} is not a directory.")
ValueError: data/NIST8398-20240828.hard-filtered.gvcf.gz is not a directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/Ancestry/igm_churchill_ancestry/__main__.py", line 4, in <module>
    run_ancestry()
  File "/opt/Ancestry/igm_churchill_ancestry/cli.py", line 131, in run_ancestry
    raise RuntimeError
RuntimeError
```

I've looked through the the functions mentioned and I can't figure out why it's treating my gvcf.gz file as a directory. Could be a pathing issue?

The gvcf is also HUGE (23.5 GB), that could be causing an issue?

Best,
Austin

**Comment by audrey-bollas** [comment]
Let me take a look... I'm not sure why it's setting directory to true here but you could be right about the file size.

**Comment by LVMEHINOVIC** [comment]
Hii!

I ran into a similar issue and traced it back to the get_extension function in /opt/Ancestry/igm_churchill_ancestry/utilities/utilities.py. This function decides whether the input is treated as a file or a directory based on the substring after the last dot (.).

When a file has an extra dot—e.g., such as in your "NIST8398-20240828.hard-filtered.gvcf.gz" case and my sample.g.vcf.gz file—the function might incorrectly detect it as a directory, leading to errors like:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/bf2d146f5c744a36844cdad41f170ef9/input/'

if I passed it as a directory path, and:

ValueError: /data/sample.g.vcf.gz is not a directory.

if I passed it as a file path.

To confirm, I changed the filename to sample.vcf.gz (removing the extra dot and the "g"), and the code worked correctly in both file and directory modes. It looks like get_extension needs to be updated to handle more complex filenames (e.g., sample.g.vcf.gz or sample.hard-filtered.gvcf.gz). 

Hopefully this helps anyone running into the same error!

**Comment by andreirajkovic** [comment]
@LVMEHINOVIC  is correct. @audrey-bollas this should be a straightforward fix. I'll try and put out a PR tonight

**Comment by audrey-bollas** [comment]
Thanks @andreirajkovic! I've updated this, and it should work with your "NIST8398-20240828.hard-filtered.gvcf.gz" filename as expected now.
See #19
